In [2]:
pip install tensorflow


In [3]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [5]:
a=tf.constant(5)
print(a)

v=tf.constant([1,2,3,4])
print(v)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [13]:
t = tf.constant([
    [[1,2,3],
     [4,5,6]],

    [[7,8,9],
     [10,11,12]]
])
print(t)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [7]:
m = tf.constant([[1,2],[3,4],
                 [5,6],[7,8]])
print(m)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)


In [14]:
a=tf.constant([10, 20, 30])
b=tf.constant([50, 60, 70])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tf.Tensor([ 60  80 100], shape=(3,), dtype=int32)
tf.Tensor([-40 -40 -40], shape=(3,), dtype=int32)
tf.Tensor([ 500 1200 2100], shape=(3,), dtype=int32)
tf.Tensor([0.2        0.33333333 0.42857143], shape=(3,), dtype=float64)


In [11]:
a = tf.constant([10, 20, 30])
print(a.dtype)
print(a.shape)

#important
print(tf.rank(a))

<dtype: 'int32'>
(3,)
tf.Tensor(1, shape=(), dtype=int32)


In [12]:
import numpy as np
np_array = np.array([[1,2,3],[4,5,6]])

tensor=tf.convert_to_tensor(np_array, dtype=tf.float32)
print(tensor)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
